FIELDS = [
    ("dof", "Date of Filing"),
    ("pet_name", "Appellant/Petitioner/Plaintiff/Complianant Name"),
    ("res_name", "Respondent/Defendant/Accused Name"),
    ("petitioner", "Appellant/Petitioner/Plaintiff/Complianant Full Details"),
    ("respondent", "Respondent/Defendant/Accused Full Details"),
    ("address_for_service", "Address for Service"),
    ("district", "District"),
    ("adv_name", "Advocate Name"),
    ("lcod", "Lower Court Order Date"),
    ("case_no", "Case Number"),
    ("lower_court_name", "Lower Court Name"),
    ("aff_oath", "Name of Deponent"),
    ("interim_prayer", "Interim Prayer"),
]
