FIELDS = [
    ("dof", "Date of Filing"),
    ("pet_name", "Plaintiff Name"),
    ("res_name", "Defendant Name"),
    ("lower_court_name", "Lower Court Name"),
    ("case_no", "Case Number"),
    ("petitioner", "Plaintiff Full Details"),
    ("respondent", "Defendant Full Details"),
    ("summons_address", "Summons Address"),
    ("lcod", "Lower Court Order Date"),
    ("district", "District"),
    ("adv_name", "Advocate Name"),
    ("aff_oath", "Name of Deponent"),
    ("interim_prayer", "Interim Prayer"),
]
