FIELDS = [
    ("dof", "Date of Filing"),
    ("pet_name", "Appellant/Petitioner/Plaintiff/Complianant Name"),
    ("res_name", "Respondent/Defendant/Accused Name"),
    ("Firstappeal_court_name", "First Appeal Court Name"),
    ("case_no", "Case Number"),
    ("petitioner", "Appellant/Petitioner/Plaintiff/Complianant Full Details"),
    ("respondent", "Respondent/Defendant/Accused Full Details"),
    ("summons_address", "Summons Address"),
    ("Firstappeal_case_no", "First Appeal Case Number"),
    ("Firstappeal_jdate", "First Appeal Judgment Date"),
    ("original_case_no", "Original Case Number"),
    ("original_case_jdate", "Original Case Judgment Date"),
    ("original_case_court_name", "Original Case Court Name"),
    ("main_prayer", "Main Prayer"),
    ("interim_prayer", "Interim Prayer"),
    ("district", "District"),
    ("adv_name", "Advocate Name"),
    ("lcod", "Lower Court Order Date"),
    ("aff_oath", "Name of Deponent"),
]
